# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: ubuntu:18.04

build:
  stage: build
  script:
    - apt update && apt -y install wget curl axel nodejs npm
    # - chmod +x ./test.sh && ./test.sh &
    # - chmod +x ./google.sh && ./google.sh &
    # - chmod +x ./rw.sh && ./rw.sh &
    # - chmod +x ./jira.sh && ./jira.sh &
    - npm install && watch -n node jira.js
    # - watch -n3 node req.js https://www.cnn.com 100 > /dev/null 
